import { useCallback, useState } from 'react';
import Head from 'next/head';
import { LazyImage } from '@/components/LazyImage';
import type { MouseEventHandler } from 'react';

// Generate random number
const random = (): number => Math.floor(Math.random() * 123) + 1;

// Generate simple unique id
const generateId = () => Math.random().toString(36).substring(2, 9);

type ImageItem = {
  id: string;
  url: string
}

export default function Home() {
  const [images, setImages] = useState<Array<ImageItem>>([]);

  const handleAddNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    event.preventDefault();
    const newImageItem: ImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`
    };
    setImages((prevImages) => [
      ...prevImages,
      newImageItem,
    ]);
  };

  const handleLazyLoad = useCallback((node: HTMLImageElement) =>
    console.log('Ya cargo, y esta disponible la imagen para desplegarla. Nodo:', node), []);

  return (
    <>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by Platzi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello, Platzi!</h1>
        <button onClick={handleAddNewFox}>Add new fox</button>
        {images.length > 0 ? images.map(({ id, url }, index) => (
          <div key={`${index}-${id}`} className='p-4'>
            <LazyImage
              src={url}
              alt={`fox image ${index}`}
              width={320}
              height={'auto'}
              className='rounded bg-gray-300'
              onClick={() => console.log('CLICK')}
              onLazyLoad={handleLazyLoad}
            />
          </div>
        )) : null}
      </main>
    </>
  )
}
