import { useState } from 'react';
import Head from 'next/head';
import { RandomFoxExplicit } from '@/components/RandomFox';

// Generate random number
const random = (): number => Math.floor(Math.random() * 123) + 1;

// Generate simple unique id
const generateId = () => Math.random().toString(36).substring(2, 9);

type ImageItems = {
  id: string;
  url: string
}

export default function Home() {
  const [images, setImages] = useState<Array<ImageItems>>([
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` },
    { id: generateId(), url: `https://randomfox.ca/images/${random()}.jpg` }
  ]);

  const handleAddNewFox = () => {
    const newImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`
    };
    setImages((prevImages) => ({
      ...prevImages,
      newImageItem,
    }));
  };

  return (
    <>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by Platzi" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello, Platzi!</h1>
        <button onClick={handleAddNewFox}>Add new fox</button>
        {images.map(({ id, url }, index) => (
          <div key={`${index}-${id}`} className='p-4'>
            <RandomFoxExplicit image={url} alt={`fox image ${index}`} />
          </div>
        ))}
      </main>
    </>
  )
}
